[platformio]
default_envs = mik32v2

[env:mik32v2]
platform = https://github.com/MikronMIK32/platform-mik32.git
board = mik32v2
framework = baremetal
monitor_speed = 115200
build_flags =
  -Iinclude
  -Imodel
  -DMAX_TEST_VECTOR_BYTES=1024
  -DMAX_BATCH=64
  -DPROTO_TIMEOUT_MS=2000

; Examples: replace with actual uploader/debugger command for your board setup
upload_protocol = custom
upload_command = python -m tools.runner.mik32_upload "$SOURCE"
